---
- hosts: droplets

  vars_files:
    - vars/main.yml

  remote_user: root
  tasks:
  - name: Install build-essential
    apt: pkg=build-essential state=latest
    register: buildessential_installed

  - name: Install pip
    apt: pkg=python-pip state=latest
    when: buildessential_installed|success

