---
- hosts: all
  roles:
    - buildtools
    - redis
    - supervisor
    - iptables
    - newrelic

- hosts: dbserver
  roles:
    - rethinkdb

- hosts: webserver
  roles:
    - nginx
    - celery
    - uwsgi
